apiVersion: v1
kind: Template
metadata:
  name: "apicast-token-headers-policy"
message: "APIcast Token Introspection With Headers Policy"
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
    labels:
      app: apicast
    name: apicast-image
  spec:
    lookupPolicy:
      local: false
    tags:
      - name: '${AMP_RELEASE}'
        annotations:
          openshift.io/display-name: AMP APIcast ${AMP_RELEASE}
        from:
          kind: DockerImage
          name: 'registry.redhat.io/3scale-amp2/apicast-gateway-rhel8:3scale${AMP_RELEASE}'
        referencePolicy:
          type: Source

- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
    labels:
      app: apicast
    name: apicast-policy

- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
    labels:
      app: apicast
    name: apicast-token-with-headers-policy
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: apicast-policy:tokenintrospect
    source:
      git:
        uri: https://github.com/fceresol/token_introspection_with_headers.git
        ref: 'master'
      type: Git
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: 'apicast-image:${AMP_RELEASE}'

- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
    labels:
      app: apicast
    name: apicast-custom-policies
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: 'apicast-image:custom'
    postCommit:
      args:
        - '--test'
        - '--lazy'
      command:
        - bin/apicast
    resources: {}
    runPolicy: Serial
    source:
      images:
        - from:
            kind: ImageStreamTag
            name: 'apicast-policy:tokenintrospect'
          paths:
            # copy policy source code into the new image
            - destinationDir: policies
              sourcePath: /opt/app-root/policies/token_introspection_with_headers
            # copy also installed dependencies to the policy folder, so they are vendored
            # - destinationDir: policies/policies/token_introspection_with_headers/0.1/resty/
            #   sourcePath: /opt/app-root/src/lua_modules/share/lua/5.1/resty/iputils.lua
      type: Dockerfile
      dockerfile: |
        FROM scratch
        COPY . src
        ENV http_proxy=
        ENV https_proxy=
        ENV no_proxy=
        ENV HTTP_PROXY=
        ENV HTTPS_PROXY=
        ENV NO_PROXY=
        USER root

    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: 'apicast-image:${AMP_RELEASE}'
      type: Docker
    triggers:
      - type: ConfigChange
      - type: ImageChange

parameters:
- name: AMP_RELEASE
  required: true
  description: AMP Version (eg. 2.2.0-GA)
